version: '3'
services:
  wikidb:
    image: mongo:3
    expose:
      - '27017'
    command: '--smallfiles --bind_ip ::,0.0.0.0'
    environment:
      - 'MONGO_LOG_DIR=/dev/null'
    volumes:
      - ./data/mongo:/data/db
  wikijs:
    image: 'kirushka/wiki-v1:1'
    entrypoint: ['node', 'server']
    links:
      - wikidb
    depends_on:
      - wikidb
    ports:
      - '80:80'
      - '3000:3000'
    tty: true
    environment:
      WIKI_ADMIN_EMAIL: admin@example.com
    volumes:
      - ./config.yml:/var/wiki/config.yml
      - ./repo:/var/wiki/repo
